config/routes.rb
Blog::Application.routes.draw do

   root 'welcome#index'
  resource :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def edit
  end

    def show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1> Edit article </h1>
<%= link_to 'accueil', root_path%>

app/views/articles/new.html.erb
<h1> Nouvel article </h1>



<%= link_to 'accueil', root_path%>

app/views/articles/show.html.erb
<h1> show article </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello rails</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'My Blog', edit_articles_path %>
<%= link_to 'My BlogNouvel article', new_articles_path %>